name: pr-review
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  data-review:
    uses: linz/topographic-system/.github/workflows/data-review.yml@master
    with:
      runs_on: ubuntu-latest_8core
      environment: nonprod
      changed_datasets_only: false
      output: s3://linz-topography-nonprod/
      strategy: ${{ (github.ref == 'refs/heads/master' && github.event_name == 'push') && 'latest,date' || format('commit={0}', github.sha) }}
    secrets: inherit

  visual-diff:
    needs: data-review
    uses: linz/topographic-system/.github/workflows/visual-diff.yml@feat/filter-catalog-gitsha
    with:
      environment: nonprod
      map_version: git-c3a9866acb0cc844a115b401f3fe011c4a9d4b7f
      project: https://d1jzh93b1t1cv.cloudfront.net/qgis/nztopo50/latest/nztopo50.json
      strategy: ${{ (github.ref == 'refs/heads/master' && github.event_name == 'push') && '' || format('commit={0}', github.sha) }}
    secrets: inherit
